// runtime/jni/jni_onload.cpp
#include "jni_onload.h"

#include <cstdio>
#include <cstring>
#include <stdexcept>

// elfuse defines PF_R/W/X; undef before pulling in system elf.h to avoid
// the -Wmacro-redefined warnings from bionic's linux/elf.h.
extern "C" {
    #include "core/elf.h"
}
#ifdef PF_R
#  undef PF_R
#  undef PF_W
#  undef PF_X
#endif
#include <elf.h>    // Elf64_Ehdr, Elf64_Sym — host-side ELF parsing only

extern "C" {
    #include "core/guest.h"
}

#include <Hypervisor/Hypervisor.h>

namespace muplar::runtime::jni {

// ────────────────────────────────────────────────────────────────────────────
// GPA arena layout (128 bytes total):
//
//  +0x00  java_vm_table : 8 slots × 8 bytes = 64 bytes  (JNIInvokeInterface)
//  +0x40  java_vm_ptr   : 8 bytes   — JavaVM* seen by the guest
//  +0x48  jni_env_ptr   : 8 bytes   — JNIEnv** seen by the guest
//  +0x50  (free)
// ────────────────────────────────────────────────────────────────────────────
static constexpr uint64_t OFFSET_VM_TABLE  = 0x00;
static constexpr uint64_t OFFSET_VM_PTR    = 0x40;
static constexpr uint64_t OFFSET_ENV_PTR   = 0x48;
static constexpr uint64_t ARENA_SIZE       = 0x80;

JniOnLoad::JniOnLoad(guest_t*   guest,
                     JniBridge* bridge,
                     JniEnv*    env,
                     uint64_t   arena_gpa)
    : guest_(guest)
    , bridge_(bridge)
    , env_(env)
    , arena_gpa_(arena_gpa)
{}

// ────────────────────────────────────────────────────────────────────────────
void JniOnLoad::write_u64(uint64_t gpa, uint64_t value)
{
    if (guest_write(guest_, gpa, &value, sizeof(value)) != 0) {
        std::fprintf(stderr, "[JNI_OnLoad] write_u64 failed at GPA 0x%llx\n",
                     (unsigned long long)gpa);
    }
}

// ────────────────────────────────────────────────────────────────────────────
void JniOnLoad::install()
{
    java_vm_table_gpa_ = arena_gpa_ + OFFSET_VM_TABLE;
    java_vm_ptr_gpa_   = arena_gpa_ + OFFSET_VM_PTR;
    jni_env_ptr_gpa_   = arena_gpa_ + OFFSET_ENV_PTR;

    // ── Zero the arena ────────────────────────────────────────────────────
    uint8_t zeroes[ARENA_SIZE] = {};
    guest_write(guest_, arena_gpa_, zeroes, ARENA_SIZE);

    // ── JNIInvokeInterface stubs ──────────────────────────────────────────
    // We only need GetEnv (slot 6) and AttachCurrentThread (slot 4).
    // Both return our JNIEnv*.  We write the jni_env_ptr_gpa as the value
    // so that when the guest dereferences JNIEnv** it gets our table GPA.
    //
    // Real stubs would be HVC thunks.  For JNI_OnLoad the only invoked slot
    // is GetEnv (called via (*vm)->GetEnv(vm, &env, JNI_VERSION_1_6)).
    // We handle the HVC in try_intercept() using call_nr 0x1FF0 (GetEnv)
    // and 0x1FF1 (AttachCurrentThread) — outside the main JNI range so they
    // don't collide with JNIEnv calls.
    //
    // Each stub GPA value here is the HVC shim entry for that slot.
    // For now we point all active slots to the same sentinel GPA and let
    // try_intercept() figure out which slot was called via X8.
    //
    // Layout of the stub: generated by elfuse shim as:
    //   movz x8, #<call_nr>
    //   hvc  #5
    //   ret
    //
    // The shim_stub_base for JavaVM slots starts at JNI stub area + 0x100
    // to leave room for the 16 JNIEnv stubs (each 8 bytes).
    // Adjust if your shim layout differs.
    // JavaVM HVC call numbers (used by try_intercept, stubs TBD)
    // 0x1FF0 = GetEnv, 0x1FF1 = AttachCurrentThread,
    // 0x1FF2 = DetachCurrentThread, 0x1FF3 = DestroyJavaVM
    [[maybe_unused]] static constexpr uint32_t HVC_GETENV  = 0x1FF0;
    [[maybe_unused]] static constexpr uint32_t HVC_ATTACH  = 0x1FF1;
    [[maybe_unused]] static constexpr uint32_t HVC_DETACH  = 0x1FF2;
    [[maybe_unused]] static constexpr uint32_t HVC_DESTROY = 0x1FF3;

    // We write stub GPAs computed from bridge_->stub_base_for_vm():
    // For simplicity, reuse the same sentinel: the bridge returns a scratch
    // stub GPA that fires HVC 0x1FF0 for all JavaVM slots.  The actual slot
    // index is passed in X1 (the "this" JavaVM pointer value identifies the
    // slot implicitly in real JNI; here we distinguish by call_nr in X8).
    //
    // If the bridge hasn't exposed stub GPAs for the VM table, we write 0
    // (will crash-on-call with a data abort — safe and diagnosable).
    //
    // TODO: bridge_->vm_stub_gpa(HVC_GETENV) once bridge exposes it.
    uint64_t stub_getenv  = 0; // bridge_->vm_stub_gpa(HVC_GETENV)
    uint64_t stub_attach  = 0; // bridge_->vm_stub_gpa(HVC_ATTACH)
    uint64_t stub_detach  = 0; // bridge_->vm_stub_gpa(HVC_DETACH)
    uint64_t stub_destroy = 0; // bridge_->vm_stub_gpa(HVC_DESTROY)

    write_u64(java_vm_table_gpa_ + 3 * 8, stub_destroy);
    write_u64(java_vm_table_gpa_ + 4 * 8, stub_attach);
    write_u64(java_vm_table_gpa_ + 5 * 8, stub_detach);
    write_u64(java_vm_table_gpa_ + 6 * 8, stub_getenv);
    write_u64(java_vm_table_gpa_ + 7 * 8, stub_attach); // AttachAsDaemon

    // ── java_vm_ptr points to the table ───────────────────────────────────
    write_u64(java_vm_ptr_gpa_, java_vm_table_gpa_);

    // ── jni_env_ptr points to the JNIEnv table installed by JniBridge ─────
    write_u64(jni_env_ptr_gpa_, env_->jni_interface_gpa());

    std::fprintf(stderr,
        "[JNI_OnLoad] install: vm_table=0x%llx vm_ptr=0x%llx env_ptr=0x%llx\n",
        (unsigned long long)java_vm_table_gpa_,
        (unsigned long long)java_vm_ptr_gpa_,
        (unsigned long long)jni_env_ptr_gpa_);
}

// ────────────────────────────────────────────────────────────────────────────
// find_jni_onload — scan the .so's dynsym on the host for "JNI_OnLoad".
//
// so_load_base: GPA where the dynamic linker placed the .so.
// so_path:      host filesystem path to the same .so (for symbol table read).
//
// We open the file on the host, walk Elf64_Shdr → SHT_DYNSYM, and find
// the symbol "JNI_OnLoad".  Its st_value (relative to 0) is added to
// so_load_base to get the live GPA.
// ────────────────────────────────────────────────────────────────────────────
uint64_t JniOnLoad::find_jni_onload(uint64_t           so_load_base,
                                     const std::string& so_path)
{
    FILE* f = std::fopen(so_path.c_str(), "rb");
    if (!f) {
        std::fprintf(stderr, "[JNI_OnLoad] cannot open %s\n", so_path.c_str());
        return 0;
    }

    // Read ELF header
    Elf64_Ehdr ehdr;
    if (std::fread(&ehdr, sizeof(ehdr), 1, f) != 1) {
        std::fclose(f);
        return 0;
    }
    if (std::memcmp(ehdr.e_ident, ELFMAG, SELFMAG) != 0 ||
        ehdr.e_ident[EI_CLASS] != ELFCLASS64 ||
        ehdr.e_machine != EM_AARCH64) {
        std::fprintf(stderr, "[JNI_OnLoad] %s is not AArch64 ELF64\n",
                     so_path.c_str());
        std::fclose(f);
        return 0;
    }

    // Walk section headers looking for SHT_DYNSYM
    uint64_t dynsym_off  = 0;
    uint64_t dynsym_size = 0;
    uint64_t dynstr_off  = 0;

    for (int i = 0; i < ehdr.e_shnum; ++i) {
        Elf64_Shdr shdr;
        std::fseek(f, static_cast<long>(ehdr.e_shoff + i * ehdr.e_shentsize), SEEK_SET);
        if (std::fread(&shdr, sizeof(shdr), 1, f) != 1) break;

        if (shdr.sh_type == SHT_DYNSYM) {
            dynsym_off  = shdr.sh_offset;
            dynsym_size = shdr.sh_size;
            // Associated string table is shdr.sh_link
            Elf64_Shdr strshdr;
            std::fseek(f, static_cast<long>(ehdr.e_shoff + shdr.sh_link * ehdr.e_shentsize), SEEK_SET);
            if (std::fread(&strshdr, sizeof(strshdr), 1, f) == 1)
                dynstr_off = strshdr.sh_offset;
            break;
        }
    }

    if (!dynsym_off || !dynstr_off) {
        std::fprintf(stderr, "[JNI_OnLoad] no DYNSYM in %s\n", so_path.c_str());
        std::fclose(f);
        return 0;
    }

    // Walk symbols
    size_t sym_count = dynsym_size / sizeof(Elf64_Sym);
    std::fseek(f, static_cast<long>(dynsym_off), SEEK_SET);

    for (size_t i = 0; i < sym_count; ++i) {
        Elf64_Sym sym;
        if (std::fread(&sym, sizeof(sym), 1, f) != 1) break;

        if (sym.st_name == 0) continue;

        char name[256] = {};
        long cur = std::ftell(f);
        std::fseek(f, static_cast<long>(dynstr_off + sym.st_name), SEEK_SET);
        std::fread(name, 1, sizeof(name) - 1, f);
        std::fseek(f, cur, SEEK_SET);

        if (std::strcmp(name, "JNI_OnLoad") == 0) {
            std::fclose(f);
            uint64_t gpa = so_load_base + sym.st_value;
            std::fprintf(stderr,
                "[JNI_OnLoad] found JNI_OnLoad: st_value=0x%llx → GPA=0x%llx\n",
                (unsigned long long)sym.st_value,
                (unsigned long long)gpa);
            return gpa;
        }
    }

    std::fprintf(stderr, "[JNI_OnLoad] JNI_OnLoad not found in %s\n",
                 so_path.c_str());
    std::fclose(f);
    return 0;
}

// ────────────────────────────────────────────────────────────────────────────
// call_jni_onload
//
// Sets up the vCPU registers and re-enters the run loop until the sentinel
// HVC fires (LR = shim stub for HVC 0x1FFF).
// ────────────────────────────────────────────────────────────────────────────
int JniOnLoad::call_jni_onload(
    uint64_t        jni_onload_gpa,
    hv_vcpu_t       vcpu,
    hv_vcpu_exit_t* vexit,
    std::function<int(hv_vcpu_t, hv_vcpu_exit_t*, guest_t*)> run_loop_cb)
{
    // ── Save current PC/LR so we can restore after JNI_OnLoad ─────────────
    uint64_t saved_pc, saved_lr, saved_x0, saved_x1;
    hv_vcpu_get_reg(vcpu, HV_REG_PC, &saved_pc);
    hv_vcpu_get_reg(vcpu, HV_REG_LR, &saved_lr);
    hv_vcpu_get_reg(vcpu, HV_REG_X0, &saved_x0);
    hv_vcpu_get_reg(vcpu, HV_REG_X1, &saved_x1);

    // ── Set X0 = JavaVM* (points to our JavaVM pointer) ───────────────────
    hv_vcpu_set_reg(vcpu, HV_REG_X0, java_vm_ptr_gpa_);

    // ── Set X1 = 0 (reserved, ignored by JNI_OnLoad) ──────────────────────
    hv_vcpu_set_reg(vcpu, HV_REG_X1, 0);

    // ── Set LR = sentinel HVC stub GPA so JNI_OnLoad's ret fires it ───────
    // TODO: replace with the real stub GPA from the shim area.
    // For now we use 0xDEAD0000 — the data abort it causes is diagnosable.
    // Once bridge exposes vm_stub_gpa(HVC_JNI_ONLOAD_RETURN), use that.
    static constexpr uint64_t SENTINEL_LR = 0xDEAD0000ULL;
    hv_vcpu_set_reg(vcpu, HV_REG_LR, SENTINEL_LR);

    // ── Set PC = JNI_OnLoad entry ──────────────────────────────────────────
    hv_vcpu_set_reg(vcpu, HV_REG_PC, jni_onload_gpa);

    std::fprintf(stderr,
        "[JNI_OnLoad] calling JNI_OnLoad at GPA 0x%llx (JavaVM*=0x%llx)\n",
        (unsigned long long)jni_onload_gpa,
        (unsigned long long)java_vm_ptr_gpa_);

    onload_returned_ = false;
    onload_retval_   = 0;

    // ── Re-enter the run loop; try_intercept() sets onload_returned_ ──────
    run_loop_cb(vcpu, vexit, guest_);

    // ── Restore registers ─────────────────────────────────────────────────
    hv_vcpu_set_reg(vcpu, HV_REG_PC, saved_pc);
    hv_vcpu_set_reg(vcpu, HV_REG_LR, saved_lr);
    hv_vcpu_set_reg(vcpu, HV_REG_X0, saved_x0);
    hv_vcpu_set_reg(vcpu, HV_REG_X1, saved_x1);

    int ret = static_cast<int>(onload_retval_);
    std::fprintf(stderr, "[JNI_OnLoad] JNI_OnLoad returned %d\n", ret);
    return ret;
}

// ────────────────────────────────────────────────────────────────────────────
// try_intercept — called from the HVC exit handler in guest_runner.cpp
//
// hvc_nr   : the immediate in `hvc #N` — elfuse uses HVC #5 for Linux
//            syscalls; we reserve a separate range so there is no collision.
//            Call this only when the ESR syndrome indicates an HVC and X8
//            is in range [0x1000, 0x1FFF].
// regs[8]  : X0..X7 from the vCPU at the HVC site.
// x0_out   : write the return value here; caller writes it back to X0.
//
// Returns true if we consumed the call.
// ────────────────────────────────────────────────────────────────────────────
bool JniOnLoad::try_intercept(uint32_t       hvc_nr,
                               const uint64_t regs[8],
                               uint64_t*      x0_out)
{
    // We only handle our JNI range
    if (hvc_nr < 0x1000 || hvc_nr > 0x1FFF) return false;

    if (hvc_nr == HVC_JNI_ONLOAD_RETURN) {
        // JNI_OnLoad returned; X0 has the return value
        onload_retval_   = regs[0];
        onload_returned_ = true;
        *x0_out = 0;
        return true;
    }

    // Route to JniBridge for all other JNI calls (0x1000–0x10FF)
    *x0_out = bridge_->handle_hvc(hvc_nr, const_cast<uint64_t*>(regs));
    return true;
}

} // namespace muplar::runtime::jni
